# Generated by Django 5.1 on 2024-08-21 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asiantouragency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='desitination_country',
            new_name='dest_country',
        ),
    ]
